### ISSUE TITLE
Major bug

### ISSUE THREAD

**Issue by nallown** [Glitch-is/ARTI-NOAH#1]
MAJOR BUG!
https://github.com/Glitch-is/ARTI-NOAH#authors doesn't include "the best man, me"

causes a critical failure in the system and brings huge security flaws.
Whole thing is vulnerable to simple hack attacks now.

Should be fixed.

**Comment by Glitch-is** [comment]
We regret to inform you that is an intended flaw in our system.

**Comment by nallown** [comment]
How dare you! Watch when I tell the FBI and CIA...
